### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by Tamriel** [AleksTk/table-logger#3]
I get

Traceback (most recent call last):
  File "/home/tamriel/Dokumente/Programmieren/hybris/hybris/course_assignment_csp_solver/tests.py", line 18, in <module>
    tbl(1, 'Row1', datetime.now(), math.pi)
  File "/home/tamriel/.local/lib/python3.5/site-packages/table_logger/table_logger.py", line 144, in **call**
    self.setup(*args)
  File "/home/tamriel/.local/lib/python3.5/site-packages/table_logger/table_logger.py", line 225, in setup
    self.print_header()
  File "/home/tamriel/.local/lib/python3.5/site-packages/table_logger/table_logger.py", line 244, in print_header
    self.print_line(self.make_horizontal_border())
  File "/home/tamriel/.local/lib/python3.5/site-packages/table_logger/table_logger.py", line 267, in print_line
    self.file.write(text.encode(self.encoding))
TypeError: write() argument must be str, not bytes

Python 3.5

**Comment by AleksTk** [comment]
For now, you can install the package from the master branch. I'll make a pypi release soon.

**Comment by AleksTk** [comment]
fixed in v0.3.2
